# Generated by Django 4.1.13 on 2024-04-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_alter_feedback_type_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.SmallIntegerField(choices=[(2, 'Image'), (1, 'Article'), (3, 'Video')]),
        ),
    ]
